### ISSUE TITLE
Support of inline comment

### ISSUE THREAD

**Issue by ranvis** [bee4/robots.txt#7]
The draft http://www.robotstxt.org/norobots-rfc.txt
defines inline comment like the following possible:

User-agent: crawler
Disallow: /no#comment

User-agent: crawler
Disallow: /no # comment

Would you think the component support this feature?

**Comment by shulard** [comment]
Hello,

For the moment, the component doesn't support his feature.
It'll be easy to add it :smile:.

Do you want to work on a PR ?

**Comment by shulard** [comment]
Fixed by: 408ab2a96f6c156308fefa5a51b70b6b0cd8c1b8

Thanks :+1:

**Comment by ranvis** [comment]
Confirmed on HEAD. Thanks!

**Comment by shulard** [comment]
Cool, the release is published as v2.0.3.
Thanks a lot for your feedback, I'm glad that there are others devs who are using my code :smiley: !
